[package]
name = "tide"
version = "0.1.0"
edition = "2024"

[dependencies]
floem = { git = "https://github.com/lapce/floem" }

[target.'cfg(target_os = "macos")'.dependencies]
alacritty_terminal = "0.25.1"
portable-pty = "0.9.0"
arboard = "3"
